### ISSUE TITLE
Add possibility to create legacy mages to settings

### ISSUE THREAD

**Issue by on3iro** [on3iro/aeons-end-randomizer#14]

**Comment by jquelin** [comment]
This has 2 sides:
1. allow the specify the number of mages created
2. name the mages

**Comment by on3iro** [comment]
Hm I am no longer sure that we actually want to build this. In our experience using `Legacy 1/2/3/4` turned out to be enough. While it would be a nice touch to have your own named mages in there it would also add additional clutter to the app. I am therefore closing this for now. We might come back to this later. But there are currently many more important features.
