### ISSUE TITLE
Refactoring: Components

### ISSUE THREAD

**Issue by jannydiamond** [on3iro/aeons-end-randomizer#142]
UI components will be refactored and reorganized according to the atomic design pattern.

- [ ] Integrate Storybook
- [ ] Create components which are used throughout the app
- [ ] Integrate components into the app

Correlates with issue #74

**Comment by on3iro** [comment]
## Costly components (especially with transitions enabled)
* [ ] drawer
* [ ] expansionpanel
* [ ] grid

**Comment by jannydiamond** [comment]
@on3iro Right now, I would prefer not to use the atomic design pattern like described in the inital issue description. Do you agree? Maybe we could have a components directory with all the components and a page directory for pages. I think its much easier to find everything :)

**Comment by jannydiamond** [comment]
We will do the tasks in this issue with issue #74. Their we will also have an eye on the costly components. So I'm closing this issue because it's more like a duplicate..
