### ISSUE TITLE
From supply randomizer, be able to "lock"/"reroll" one or many tile

### ISSUE THREAD

**Issue by loganmzz** [on3iro/aeons-end-randomizer#217]
**Is your feature request related to a problem? Please describe.**
Sometimes you're not satisfied with generated market but want to keep or just change some. It can be nice to be able to randomly re-peek some tiles based on selected ones.

**Describe the solution you'd like**
Ideally depending on UX/UI (especially regarding device type), you may add:

1. A re-roll button on each tile to be able to re-roll just this one.
UX problem: previous criterion must be remembered by user.
2. A "lock" button on each tile to be able to keep it in case of new push on "Create market" button.

**Describe alternatives you've considered**
Alternative solution is instead of reroll to have a button that revert to "unselected" state and then "Create market" button does a full refresh if there's all "selected" tile, but just refresh "unselected" if there's some.

**Additional context**
I have used randomizer for Dominion which have such features, that can help to create randomize but balanced market by avoiding some uncomfortable configuration.

**Comment by on3iro** [comment]
Hm that's an interesting feature request. We'll definitely consider adding such a feature :+1:
Likewise we might add an option to include specific cards into a supply setup.

**Comment by on3iro** [comment]
## Braindump

* [ ] Add lock icon-buttons to tiles
* [ ] Check if blueprints can be referred to by index otherwise give temporary id
* [ ] Also save index/temporary id to rolled market cards
* [ ] New state slice with list of locked market card ids
* [ ] upon rolling filter blueprints by locked market cards

**Comment by on3iro** [comment]
done with #365
