### ISSUE TITLE
From supply setup settings, adapt tile color when editing custom setup

### ISSUE THREAD

**Issue by loganmzz** [on3iro/aeons-end-randomizer#219]
**Is your feature request related to a problem? Please describe.**
A color "pattern" has been choiced for the app but not apply on custom setup editor.

**Describe the solution you'd like**
Just update tile background based on tile type.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by on3iro** [comment]
I am not quite sure I understand what you are referring to.

 Do you mean that part:

![Screenshot 2019-10-25 at 14 10 16](https://user-images.githubusercontent.com/8681413/67570303-4be0e980-f731-11e9-85cc-5481cb36462a.png)

**Comment by loganmzz** [comment]
Yes, exactly this block. Its background is always grey, it would be nice that background adapt to selected type.

**Comment by on3iro** [comment]
Fix released with https://github.com/on3iro/aeons-end-randomizer/releases/tag/v2.2.0
