### ISSUE TITLE
Bug: Expedition barrack contain mages from unselected expansions?

### ISSUE THREAD

**Issue by ajwatras** [on3iro/aeons-end-randomizer#221]
When creating an expedition using default settings the barracks will show mages from expansions that I have deselected. Going through and de-selecting the mages from those expansions seems to fix the issue, but is tedious. 

For example, aeon's end war eternal mages will show up even if it isn't selected as an expansion, but if I remove dezmodia from the pool of war eternal mages, she will no longer show up.

**Comment by on3iro** [comment]
@ajwatras Thanks for reporting that bug. I will definitely look into this asap and report back :) :+1:

**Comment by on3iro** [comment]
Released with https://github.com/on3iro/aeons-end-randomizer/releases/tag/v2.2.0
