### ISSUE TITLE
Custom Narrative Expeditions (Editor + Export)

### ISSUE THREAD

**Issue by on3iro** [on3iro/aeons-end-randomizer#232]
It would be awesome if we would allow for the creation of custom expeditions including narrative screens in between. Combined with an import/export feature the community could share custom expeditions.

**Comment by vogelap** [comment]
I agree. That would be great.

**Comment by on3iro** [comment]
## Braindump

* [ ] clean up errors on successful expedition import
* [ ] create config DSL

### Things that should be included in the DSL

* Narratives and Story-branching
* Fixed nemesis, rewards etc.
* Variable amount of narratives/battles etc.
* Custom scoring

**Comment by on3iro** [comment]
## Toying around
Just toying around with some ideas on how configuration for this could look like based on our expedition export feature and structure:

```js
{
    "id": "s-eXiWqn",
    "name": "",
    "variantId": "CUSTOM",
    "bigPocketVariant": false,
    "seed": {
        "seed": "s-eXiWqn"
    },
    "settingsSnapshot": {
        "supplySetup": {
            "id": "random",
            "name": "Random Setup (Default)",
            "type": "official",
            "default": true,
            "active": true,
            "tiles": [
                ...
        },
        "availableCardIds": [
            ...
        ],
        "availableMageIds": [
          ...
        ],
        "availableNemesisIds": [
            ...
        ],
        "availableTreasureIds": [
            ...
        ],
        "availableUpgradedBasicNemesisCardIds": [
          ...
        ]
    }
}
```

**Comment by on3iro** [comment]
we might skip the separate routing and add the `nextEncounter` part directly to each branch 🤔
