### ISSUE TITLE
Seeded randomization (esp. in Expeditions)

### ISSUE THREAD

**Issue by on3iro** [on3iro/aeons-end-randomizer#233]
I would like to add some kind of randomization seed to the general randomizer as well as to the expedition feature. That way certain setups could easily be shared with one another or re-run.

**Comment by on3iro** [comment]
## Brain dump

### Import Expedition
* Configuration of the actual Expedition
* Used supply setup (full config)
* Expansion-Settings (full config)
* optional: use seed to make randomizations fully deterministic

**Comment by jannydiamond** [comment]
- [ ] use in settings selected treasures and upgraded nemesis cards instead of all available ones

**Comment by on3iro** [comment]
Closing, because this feature is merged to dev :)
