### ISSUE TITLE
1 Player 3/4 Alternate turns.

### ISSUE THREAD

**Issue by Mesclor** [on3iro/aeons-end-randomizer#271]
Switch the number of turns the 1 player gets based on the round number. For the first round player gets 3 turns nem gets 2. On the 2nd round player gets 4 rounds and the nem gets 2. Round 3 back to 3 turns. Being able to see what round it is would also be great to track when won or lost the game.

**Comment by on3iro** [comment]
I just built this and will make a release in the next couple of minutes. The only part missing is the display of which turn you are at. I am currently not sure if I want to add this. Maybe we'll add a round counter in the future :)

**Comment by on3iro** [comment]
ok there seems to be a bug - ill make a quick rollback and see if i can fix this in the next couple of minutes

**Comment by on3iro** [comment]
should be fixed
