### ISSUE TITLE
RFE: Language translation

### ISSUE THREAD

**Issue by loganmzz** [on3iro/aeons-end-randomizer#298]
### Is your feature request related to a problem? Please describe.

I'm a French player and using French core box. It takes to time to find out card as name doesn't match.

### Describe the solution you'd like

As additionnal detail, I would like to say that some French players are mixing language content (even if there are not stricly compatible, card back is different).

So:

**Quick Win**

Just add `Expansion` for each language. It's the simplest solution I think, maybe having a way to quick filter on `Expansions` screen could help.

### Describe alternatives you've considered**

**`Expansion` language**

For each `Expansion` add a language selection.

### Additional context

Whatever the solution, I think using flag icon would be nice !

**Comment by on3iro** [comment]
hi @loganmzz - thanks for the suggestion :)

I think generally it would be rather easy to implement a language switcher. However there is one big _'BUT'_:

I am not really keen on writing out all the content. This means, if you would like to see support for different languages like french, the community would have to provide the necessary data and ideally do it in our own format. All content *ids* would have to be the exact same as in our original content. If we had that data, we could implement an easy language switcher, which would simply lookup all data by the language you have selected.

If you are able to accumulate the data and provide it, we can move forward with this. Let me know if this would be an option for you and if you need any help :)

One minor caveat: we are currently developing a very big feature, so I don't know how long it will take us until we can dedicate attention to the language switcher.

**Comment by loganmzz** [comment]
No problem to write the content.

Currently we only have wave 1 content, wave 2 was supposed to arrive this year but regarding context I'm not sure if all wave 2 content will be delivered this year. I have only the core box for the moment but will ask other French players to share.

Whatever, my proposal is to open a branch from a fork with French content and open PR so we can iterate on format, file organization, etc. Is it ok for you ?

**Comment by on3iro** [comment]
@loganmzz sounds great - thanks for helping out :) 👍

**Comment by on3iro** [comment]
## Braindump:

* [ ] Toggle all write to indexedDB
* [ ] Basic nemesis cards write to indexedDB
* [ ] check all parts, that access content
* [ ] fix tests
* [ ] build language switch
