### ISSUE TITLE
Option to reset the story expositions

### ISSUE THREAD

**Issue by dyordanovv** [on3iro/aeons-end-randomizer#308]
**Is your feature request related to a problem? Please describe.**
From time to time I introduce the game to new players and I find it the best way to reset the New Age, It will be cool if the randomizer can guide me through it

**Describe the solution you'd like**
Maybe custom seeds with the expeditinos (The new age, into the wilds, I guess Outcast will have some of these too), but since the reward are abit different from the normal expeditions maybe just another menu for playing the story expeditions.

**Describe alternatives you've considered**
Well, finding all the card numbers for the story expedition, but when you have all the expansions this gets time consuming

**Additional context**

**Comment by on3iro** [comment]
thanks for the suggestion, have a look at #232 to follow how the development of narrative expeditions goes. I am closing this, as I expect narrative expeditions to be absolutely capable of applying the experience you want.
