### ISSUE TITLE
Snackbar: For user/error messages + React error boundaries

### ISSUE THREAD

**Issue by on3iro** [on3iro/aeons-end-randomizer#317]
It would be great to have a snackbar we could show to the user, whenever something unexpected happens or when we save something etc.

Would be rather easy to build by ourselves or we could use a ready made solution

**Comment by jannydiamond** [comment]
Where we could use a snackbar:
- [ ] Create an expedition
- [ ] Delete an expedition
- [ ] Copy an expedition
- [ ] Share an expedtion
- [ ] Add custom supply setup
- [ ] Delete custom supply setup
- [ ] Save edited supply setup

**Comment by jannydiamond** [comment]
@on3iro I added an new issue for the tasks above: #487 :)
