### ISSUE TITLE
Opera browser can't get the newest version 

### ISSUE THREAD

**Issue by Gusti23** [on3iro/aeons-end-randomizer#341]
**Describe the bug**
My opera browser can't get the newest version of randomizer. It shows 2.4.1 version of it.

**To Reproduce**
1. Go to main site of randomizer with opera browser
2. Search for version
3. See error

**Expected behavior**
Allow opera browser to get the newest version of randomizer.

**Screenshots**
![image](https://user-images.githubusercontent.com/65735339/83500084-98a65300-a4be-11ea-9f25-cdcc113f7e19.png)

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [Opera]
 - Version [68.0.3618.142]

**Comment by on3iro** [comment]
Hi @Gusti23 there are multiple things you could do:

The update mechanism is a bit tricky and we will try to come up with something better. Currently it does work like this on mobile:

You open the app inside your browser and give it some time. You then have to fully close your browser. Then re-open the browser and re-open the app. The service-worker should then have loaded the new version behind the scenes.

On Desktop you can actively push your browser to load the current version, by reloading the page without caching:

Have a look  at these instructions to do so with opera https://superuser.com/questions/405811/how-to-reload-a-page-in-opera-without-cache/1244423

Let me know, if that worked for you :)

**Comment by Gusti23** [comment]
Yes, forcing browser to reload without caching makes it works. Thank you :)

**Comment by on3iro** [comment]
Great - glad it worked out for you :)
