### ISSUE TITLE
Add 'select/deselect all' toggle to settings content customization

### ISSUE THREAD

**Issue by on3iro** [on3iro/aeons-end-randomizer#371]
Like the checkbox above expansions...

**Comment by jannydiamond** [comment]
@on3iro Am I right that 'settings content customization' means a toggle inside every expansion to select all assets of that expansion or is something else meant by that?

In the future we could also add a toggle by category (e.g. a toggle for all nemeses, mages, etc inside of an expansion). Maybe we could also use this for toggling all standalone, mini, etc expansions. What do you think? Maybe that could be a separate issue. :)

**Comment by on3iro** [comment]
yes, i mean all distinct entities of each expansion.

To your second suggestion: yeah we might do that... had that though before, but it felt like ui clutter to me. Still unsure if this is useful enough to be included. So far nobody seems to miss this feature  🤷

**Comment by jannydiamond** [comment]
Thx for the clarification 👍 

Alright, for the second suggestion I have an idea to reduce ui clutter but I'm going to open another issue where we could discuss this. Maybe you're right and we don't need this enhancement (yet 😄)
