### ISSUE TITLE
Update types for Outcasts

### ISSUE THREAD

**Issue by on3iro** [on3iro/aeons-end-randomizer#383]
We need to update the following types to display variants of the outcasts expansions correctly:

Nemesis:

    health of nemesis should be number | string because the health of Experiment 153 (Outcasts) is *, where * is 20 health per maw

Mage:

    charges should be number | "Custom" | string or just a string because Cairna (Return To Gravehold) has 3-6 charges where 3 are Overcharges
    mageTitle should be optional because all mages in the 5th wave have no mage titles

**Comment by Torgen** [comment]
I think these are all done.
