### ISSUE TITLE
Add card library

### ISSUE THREAD

**Issue by on3iro** [on3iro/aeons-end-randomizer#40]

**Comment by jannydiamond** [comment]
- Show details of a card via an eye-icon button which opens a layer
- Show tags/keywords for supply cards in the settings section
- Add library page
- Add filtering and sorting of library (tbd)

**Comment by on3iro** [comment]
i don't think we will add any additional library feature, as all information is easily accessible via the settings. maybe we add filtering there, but thats another story ;) therefore closing
