### ISSUE TITLE
Integrate Legacy of Gravehold cards

### ISSUE THREAD

**Issue by sarathas** [on3iro/aeons-end-randomizer#449]
**Is your feature request related to a problem? Please describe.**
I want to play with the new cards from the Legacy of Gravehold expansion.

**Describe the solution you'd like**
Import the Legacy of Gravehold expansion and its cards, nemeses and mages.

**Additional context**
Future integrations include alternative turn order cards for a special nemesis.

**Comment by aeiou871** [comment]
I could provide the list of all the cards with costs, nemesis with tiers and mages' names if someone would be willing to implement it in the app

**Comment by on3iro** [comment]
@aeiou871 @sarathas contacted me a few days ago, that he already had started implementing the cards. So he is actually doing it right now :) 

But thank you anyway 👍😊

**Comment by aeiou871** [comment]
Actually, we were just playing an expedition and rolled a card from Legacy
of Gravehold so I can see that they're being implemented! Thank you both
for great work!

sob., 8 sty 2022, 19:56 użytkownik Theo Salzmann ***@***.***>
napisał:
