### ISSUE TITLE
Adding Optional Content Settings

### ISSUE THREAD

**Issue by elmodor** [on3iro/aeons-end-randomizer#451]
**Is your feature request related to a problem? Please describe.**
The possibility to have optional community tweaks/changes which can be activated manually in the settings.

**Describe the solution you'd like**
- Inside the settings there could be a new section "Optional Content" or "Community Tweaks/Changes" with different optional settings that must be manually activated. 
- These changes could be inside the "Expedition" tab or in a new tab. They should not be activated when selecting "All".
- These changes could also be directly inside the Legacy options instead being global.

**Describe alternatives you've considered**
I'm not aware of any other alternatives.

**Additional context**
The legacy nemesis "Haze Fiend" can not be played outside of legacy. However, there is a community adaption to make it playable outside of legacy:
https://boardgamegeek.com/filepage/191166/legacy-nemesis-tweaks-regular-play
The randomizer hence should have an option to optional add Haze Fiend as additional nemesis.

Comment from on3iro: "Could be added as a separate key in the expansion"

**Comment by on3iro** [comment]
@elmodor thanks for submitting this issue. 

There might be a very easy solution to your problem, however I am not sure, if this would suite you:
Nemeses have an `additionalInfo`-Property (see Gate-Witch from **War Eternal** for example). We could simply add Haze Fiend to the Legacy expansion and add the community tweaks to the additional info field. That way one could simply decide to turn it on/off inside the settings like all other content and their would be no need for any additional code.

Would that help? :)

**Comment by elmodor** [comment]
That would work for me.

However, imho it should not be selected when pressing "Select All" or the "Legacy" expansion. Because then it might show up and the user might not want to fight this nemesis in the expedition because they do not have the tweaks - and there is no way to reroll the nemesis. That's counter intuitive.
So it would need to be selected explicitly. Would this be the case? How would the user know that there is such an "optional" setting to activate inside Legacy?

**Comment by on3iro** [comment]
hm, there currently is no such option. I am also not sure if the problem you describe is as big as it looks on first glance. I mean most people probably set there content manually to a degree anyway and it might even be, that they disable lots of legacy content (we usually disable legacy completely).
So I am not sure if it would be worth adding additional complexity for such a minor inconvenience (the worst that could happen is that it shows up and people decide not to fight him and "replace" him with a different nemesis and disable him from the content afterwards, so he would not show up again.

What do you mean when you say
```
[...]because they do not have the tweaks[...]
```

I haven't looked too much into the tweaks and was assuming that they are mostly some text (which we would add to the `additionalInformation`-property) and maybe some cards which are included in legacy. Or does the tweak include additional user made content you would need to print out?

If that's the case we actually might make it a "community tweaks" expansion like you suggested. That way people could simply deactivate the whole expansion and it would be more prominent inside the settings. I would add other community mods to that expansion later on.

**Comment by elmodor** [comment]
For Haze Fiend they are just setup instructions which you don't necessarily have to print out. But you will need some specific modified legacy cards (with specific stickers).
But since it states the Haze Fiend is not playable outside of the campaign, not sure if the users will have those cards stored somewhere accessible.

When I look at the randomizer settings, I know that I own all of a specific wave, I just check the whole wave. I didn't check all the nemesis and spells in every wave.

The official rulebook says Haze Fiend is not playable outside of the campaign. Because of that I think it should not be automatically included when you check "Legacy". Keep the core randomizer settings to the official rulings.

**Comment by on3iro** [comment]
@elmodor hm, I would be fine with adding a specific "community content" expansion. When you open the randomizer the very first time there is no content selected anyway.

![image](https://user-images.githubusercontent.com/8681413/148727935-98f3ff80-5c4f-4002-b642-4f0f0864ba71.png)


So this should work fine. Would you be interested in providing the "community expansions"-data?

**Comment by elmodor** [comment]
This would be the required data:
Nemesis: Haze Fiend, Expansion: Legacy, Health: 75, Difficulty: 5, Expedition tier: ? (haven't found the randomizer cards for my legacy nemesis...)

Required adjustments (by Michael Hunter):
Setup: Setup twelve crystal cards with the flawed stickers on them. These form the flawed crystal deck.
Unleash: A player degrades a card in their hand that costs 2 or more aether. OR Each player suffers 1 damage for each flawed crystal in their hand and one player places a flawed sticker on a crystal in their hand or discard pile.
Flawed Crystals: When you are instructed to place a flawed sticker on a crystal, instead destroy that crystal and replace it with a card from the flawed crystal deck.
Increased Difficulty: When a spell deals damage to the nemesis, reduce that damage by 1 for every flawed crystal in your hand to a minimum of 1.
https://boardgamegeek.com/filepage/191166/legacy-nemesis-tweaks-regular-play

Where would this data be filled in?

**Comment by on3iro** [comment]
@elmodor you would create a new Expansion (inside `src/aer-data/src/ENG`. There is also a basic [README](https://github.com/on3iro/aeons-end-randomizer/tree/main/src/aer-data) describing the process (however you don't need the build steps from that README!). You could also reference the recently added [Legacy of Gravehold-Pull Request](https://github.com/on3iro/aeons-end-randomizer/pull/454/files).

Let me know if you get stuck somewhere :) :+1:
