### ISSUE TITLE
Change general theme color

### ISSUE THREAD

**Issue by jannydiamond** [on3iro/aeons-end-randomizer#46]
Change theme color to teal and sync with splash screen and app logo color

**Comment by sarathas** [comment]
Actually, this could be generalized to make the user choose their own theme colors. 
I imagine a settings tab in the menu (chanigng the previous "settings" tab to a "sets" or "expansions" tab) where the user can set their own theme. 
There are only two colors as of right now: one for the navbar and primary buttons, one for selected radio buttons, checkboxes and so on.

**Comment by jannydiamond** [comment]
@sarathas good idea. Maybe we should open a separate issue for that? @on3iro What do you think?
