### ISSUE TITLE
Add an option to draw unique mage names

### ISSUE THREAD

**Issue by sarathas** [on3iro/aeons-end-randomizer#460]
**Is your feature request related to a problem? Please describe.**
With Legacy of Gravehold (and Outcasts to an extent), it is now possible to draw mages with the same name twice from different expeditions. In the worst case, you might draw three Taqrens. 

**Describe the solution you'd like**
Either in the global settings, or in the Mages Randomizer and the Expeditions, I want to have a checkbox that says "Draw unique mage names". When it is checked, and mages are drawn, no duplicate mage names are drawn anymore. 

**Describe alternatives you've considered**
When mages are drawn, it is possible to click single mages and have an action for them to "redraw". This might be even more cumbersome to implement but would be more of a general feature.

**Comment by on3iro** [comment]
@sarathas Good idea! Would you like to tackle this?
