### ISSUE TITLE
Data reset

### ISSUE THREAD

**Issue by dolfanatl** [on3iro/aeons-end-randomizer#466]
**Describe the bug**
3 times the webpage showed the spinning icon. It never goes away so I refresh the page. When the page finishes loading, all of my data is lost. This includes my selected expansions, custom market, and in progress expeditions.

**To Reproduce**
I don't know the trigger. It just happens.

**Expected behavior**
Data does not get reset.

**Smartphone (please complete the following information):**
 - Device: Motorola Moto G Fast
 - OS: Android Version 11
 - Browser Google Chrome
 - Version 101.0.4951.41

**Additional context**

**Comment by on3iro** [comment]
Hi @dolfanatl ,

I am really sorry, that you ran into such issues.

The bug you describe sounds very weird.

If you don't mind I have a few questions :)

1. Where exactly did you see the loading spinner icon? (where inside the app)
2. Did you somehow clear your browser cache/indexedDB?
3. Could it potentially be, that you don't have much space left on the device?
4. Did you have a lot of data inside the app (meaning quite a few expeditions, supply setups etc.)
5. When you go into chrome and type the following inside the url: `chrome://indexeddb-internals` - what is the output?

The only thing I can currently imagine why that happened, is that you somehow ran out of space (either device space or indexedDB space) and Chrome automatically tried to clean up in some way. However this is just a wild guess. I haven't heard of an issue like that before.
