### ISSUE TITLE
I would like to translate the Buried Secrets expansion to polish

### ISSUE THREAD

**Issue by on3iro** [on3iro/aeons-end-randomizer#475]
### Discussed in https://github.com/on3iro/aeons-end-randomizer/discussions/473

<div type='discussions-op-text'>

<sup>Originally posted by **Kesimux** January 30, 2023</sup>
Hi, 

I would like to translate the Buried Secrets expansion to polish, however I have no idea how to physically do it. 

Guidance would be appreciated :D</div>

**Comment by Gusti23** [comment]
@on3iro it is already translated. You can close that issue.

**Comment by on3iro** [comment]
@Gusti23 ah yeah, thanks for the reminder!
