### ISSUE TITLE
Bug: Current card selection visible in market setup after changing setup

### ISSUE THREAD

**Issue by sarathas** [on3iro/aeons-end-randomizer#48]
Setup: In the Supply tab, after creating a market with any setup, the market setup template is changed by the user (via the drop-down menu).

Expected behavior: All current market cards are cleared and the new template is shown.
Actual behavior: The new template is shown, but the market from the (now deprecated) market template is still visible. This creates an inconsistent view.

Please clear the market cards after the setup is changed.

**Comment by on3iro** [comment]
will do - thanks for bringing this up 👍
