### ISSUE TITLE
Polish Translation Card Mixup

### ISSUE THREAD

**Issue by szymczycha** [on3iro/aeons-end-randomizer#497]
**Describe the bug**
Polish description and name of card (#Id: FossilizedScarab) is mixed up with Polish description of card (#Id: HauntedBerylite)

**To Reproduce**
1. Go to Settings 
2. Set language to Polish
3. Click on "Niezbadany Mrok" (The Outer Dark)
4. Notice that the card "Skarabeusz w Bursztynie" should be in "Otchłań" section instead.
5. Click on "Otchłań" (The Void)
6. Notice that the card "Nawiedzony Beryl" should be in "Niezbadany Mrok" section instead.

**Expected behavior**
These cards should have each other's descriptions

**Screenshots**
"Otchłań" (The Void)
![image](https://user-images.githubusercontent.com/95142108/224563688-7f15ddc1-0f7f-44d9-9ac0-1bc2913aaf28.png)
Expansion expected to be (The Outer Dark)
![image](https://user-images.githubusercontent.com/95142108/224563881-9bdff6a8-658c-41b3-ad2c-993db9f7eb1e.png)

"Niezbadany Mrok" (The Outer Dark)
![image](https://user-images.githubusercontent.com/95142108/224563758-ae148484-4296-405c-b48e-518354a324bd.png)
Expansion expected to be (The Void)
![image](https://user-images.githubusercontent.com/95142108/224563798-137b38ca-a9bd-470b-ab81-70453ee402c8.png)

**Comment by on3iro** [comment]
Thanks for the report @szymczycha .

@Gusti23 would you be so kind and have a look into this? :) - would be super cool if you could fix this, if the cards are indeed mixed up.
