### ISSUE TITLE
Maybe add an icon to show market setups which are not legal by the rulebook

### ISSUE THREAD

**Issue by on3iro** [on3iro/aeons-end-randomizer#50]
A user on reddit pointed out, that some market setups are not legal - at least by the rulebook. 
While I would say these are technical legal, because the come from the designer of the game himself, it might be useful to add a small indicator, that they are not? I am not sure actually.

**Comment by jannydiamond** [comment]
Will it be possible to add custom market setups in the future? If yes, we could use a small indicator for that case anyway. Maybe we could see the setups which are not legal by the rulebook as custom setups, too?

**Comment by on3iro** [comment]
I don't know, this feature does not really make sense to me. I'll close this for now
