### ISSUE TITLE
Wave 8 Content - Contribution Discussion

### ISSUE THREAD

**Issue by deusabianca** [on3iro/aeons-end-randomizer#522]
I can slowly work on adding wave 8 content once I get it, but if anyone who gets it before me wants to do that, let us know here.

There is an issue I want to talk about regarding the turn order feature. When adding friends and foes, it should be modular. Likely with a checkbox for adding a friend and one for adding a foe, separate from the currently available modes. That way you can add friends and foes to any distinct turn order configuration (eg myth and bone), as well as play with only a friend/only a foe.

**Comment by on3iro** [comment]
@deusabianca I don't plan on ever owning the new content and am completely out of the loop regarding new rules etc. I also don't have time to work on new features. Do you think that you could make these changes to the turn order feature? Else we could create a separate issue for this with the `help wanted` label. Though I would not be too optimistic that anyone will build this.

**Comment by Torgen** [comment]
My friend has the wave 8 content and has lent it to me so I can transcribe it into the app. I can also implement the friend and foe cards in the turn order.

**Comment by on3iro** [comment]
@Torgen that's awesome! Note that @deusabianca already created a PR for one of the mini expansions: https://github.com/on3iro/aeons-end-randomizer/pull/526 - i'll try to review this asap. 

Maybe you two could split the content somewhat, such that you wouldn't have to type most of the main content all by yourself @Torgen / @deusabianca ? :)

**Comment by Torgen** [comment]
#529 means this is done?
