### ISSUE TITLE
Add some kind of market setup preview

### ISSUE THREAD

**Issue by on3iro** [on3iro/aeons-end-randomizer#63]

**Comment by jannydiamond** [comment]
I made some screens of how those previews could look like:
![AER-Supply-v1](https://user-images.githubusercontent.com/8681488/54473452-2c1b3780-47d8-11e9-8ad4-a1dc99713bef.jpeg)
![AER-Supply-v2](https://user-images.githubusercontent.com/8681488/54473453-2c1b3780-47d8-11e9-97e6-7b32b19a70b6.jpeg)
![AER-Supply-v3](https://user-images.githubusercontent.com/8681488/54473454-2c1b3780-47d8-11e9-8ca9-00c8ae50ef9e.jpeg)

What do you think?
