### ISSUE TITLE
Integrate Redux

### ISSUE THREAD

**Issue by on3iro** [on3iro/aeons-end-randomizer#65]
The app is starting to become rather complex. I think we should probably integrate redux soon, to make state handling a lot more explicit.

**Comment by sarathas** [comment]
Why do we not make use of the new Context API instead? In other words: What is the exact use case that prevents us from using Context API in favor of redux?

**Comment by on3iro** [comment]
context is nice but pretty barebones. Its not an alternative for redux and isn't meant to be. E.g. we miss out on debugging capabilities as well as organizational structure. While we could mimic some of this with excessive use of `context` and Reacts `useReducer` it still wont be the same. Furthermore it enables the use of middlewares, which will be pretty helpful going forward.

Context is nice for many things and is even used by redux under the hood. When I started the App it made sense to use it initially. But in my opinion the app reached a point where I would like to manage Application state in a sane way and Redux enables us to do so.

**Comment by on3iro** [comment]
To add to the stuff above: I don't think adding redux is bad in any way. To me it feels like the app reached that point very naturally. And in hindsight I would say that it was a great move to start without it. This way I got a better feeling for when Redux is actually necessary and when we can live without it.

**Comment by on3iro** [comment]
## Thoughts:
One MR, but integrate step by step:
* [ ] Settings first
* [ ] Nemesis
* [ ] Mages
* [ ] Supply
* [ ] TurnOrder
