### ISSUE TITLE
Add easy update method

### ISSUE THREAD

**Issue by jannydiamond** [on3iro/aeons-end-randomizer#84]
When a new version of the app is available the update screen appears.

**IS:**
After clicking the update button the app reloads, but is still showing the update screen. Only after closing the app, the update screen disappears and the app has the new version.

**SHOULD:**
After clicking the update button the app reloads and the update screen disappears. Also the app has the new version.

**Comment by on3iro** [comment]
@jannydiamond important:
before you deploy to our test server build the project with this command:
`PUBLIC_URL=/ yarn build`
Then you can deploy with:
`surge ./build`

This will be added to the README eventually... (maybe with v1.5.0 :D)

**Comment by on3iro** [comment]
we need to find another update strategy, this does not work as intended

**Comment by on3iro** [comment]
removed both labels.
The priority shouldn't be high - updating works fine, even if it takes a while for users. We released enough versions of the app, to know that this is not a big issue.
Its also no longer classified as bug, because the feature has been removed from the app and needs to be rebuild entirely.

**Comment by on3iro** [comment]
Actually - in my experience updating works fine enough. I don't feel its that painful. So we would probably waste our energy on this instead of developing something else. If this issue. pops up in the future, we can simply re-open this issue.

**Comment by on3iro** [comment]
hm, manual updates would actually be way cooler... we should have a look at this again...
