### ISSUE TITLE
CI fails because of node/jest bug

### ISSUE THREAD

**Issue by on3iro** [on3iro/aeons-end-randomizer#86]
https://github.com/facebook/create-react-app/issues/6591

**Comment by jannydiamond** [comment]
A similar issue: https://github.com/facebook/jest/issues/8069

**Comment by on3iro** [comment]
According to the latest comments inside the CRA-issue, the problem should be fixed.
I'll keep an eye on the next CRA-version.
There is an alpha of CRA containing the fix. The newest node version also seems to fix the problem.
This will probably be incorporated in the circleCI container in the next few days/weeks. So the probably might sort out itself.

**Comment by on3iro** [comment]
Pinned the node version, everything runs fine again
