### ISSUE TITLE
Change Legacy 1 ... Legacy 4 mages to "Legacy Yellow" ... "Legacy Blue"

### ISSUE THREAD

**Issue by jquelin** [on3iro/aeons-end-randomizer#88]
Legacy 1 - 4 does not say which is which. Issue #14 would be better in the end (ie, allow us to provide names of Legacy mages), but in the meantime using colors to name them is way easier to tell them apart.

**Comment by on3iro** [comment]
Good point. I was under the impression that you could simply assign the player 1-4 tokens, but those are not present in Legacy 🤔

**Comment by on3iro** [comment]
@jquelin how important is that feature for you? do you own more Aeons stuff and could use the player tokens. for now? Otherwise I could create a small hotfix. We could also just add colors to the mage cards and keep the Legacy 1-4 names

**Comment by on3iro** [comment]
We just talked this through: we will do the color names for now as you suggested.

**Comment by jquelin** [comment]
@on3iro : importance? I can live without, I know the names of my mages so I'm sorting them in my head and then pick the one randomized. But the goal of the app is to make things easy - this is one of those easy fixes.
Afterwards, I'm not a big design freak, so I don't know what's best (adding the color as background or as name)

**Comment by on3iro** [comment]
> I'm not a big design freak
Haha, me neither. I am a bit afraid of feature creep, though. Which is why I really try to iron out the importance of certain features. Adding the color refering to each Legacy mage seems reasonable, though.
