### ISSUE TITLE
New setting: market sorting

### ISSUE THREAD

**Issue by jquelin** [on3iro/aeons-end-randomizer#89]
Currently the market is sorted by type of card (gem/relic/spell). It would be nice to allow a sub-sorting (cost or alphabetic).

**Comment by on3iro** [comment]
Hm I thought a bit about this. We currently sort cards by card type as well as cost. Are there scenarios where another kind of sorting would be helpful? I assume most players have their cards sorted by type and probably by cost as well, so this would be the logical order to pick the cards from the box. 

I am going to close this for now, feel free to re-open this, if you think the feature would still be useful in certain situations. (it is still very low priority, especially as we only have very little time to dedicate to the project in the upcoming months)
