### ISSUE TITLE
Next button

### ISSUE THREAD

**Issue by jquelin** [on3iro/aeons-end-randomizer#90]
When one wants to setup a new game, we go to menu/nemeses + Open breach.
Afterwards, menu/Mages + Recruit Mages.
Then menu/Supply + Create Market.

Menu is a bit cumbersome to open, I therefore propose to add a "Go to recruit Mages" button when nemesis has been drawn, and a "Go to create Market" when mages have been recruited. I guess there should also be a "Go to turn order" after market has been created for the sake of consistency, even if I do not use the turn order feature.

**Comment by on3iro** [comment]
Hm, I know where you are coming from. This was a design decision. I wanted to make each "sub-app" as independent from the other apps as possible. Each feature should be easy to use.
On the other hand most people will use all three randomizers anyway...

I am still not sure if an additional button is worth the UI-clutter it comes with, though. Switching between apps via the menu is relatively simple.

Thanks for the suggestion, though - we should definitely discuss this further.

**Comment by jannydiamond** [comment]
@on3iro Maybe we could move settings and infos into a dot menu (left side of nav). After that we could implement a fixed navigation at the bottom ([Example Bottom](https://material.io/develop/android/components/bottom-navigation-view/)) of the app (or as tabs at the top after navigation: [Example Top](https://material-components.github.io/material-components-web-catalog/#/component/tabs)) with all 4 sup-apps. So we wouldn't need the menu anymore and could switch between apps easily because they are always visible.

**Comment by on3iro** [comment]
Hm, I don't know. I am personally not at all a fan of tab navigation in apps. I find it rather annoying. Additionally this might feel awkward, because a native android app would allow swiping between tabs and I am not sure if behavior like this is possible with a PWA

**Comment by jquelin** [comment]
Honestly I don't know what's the best UI-wise. But I think that people doing the randomization will use the 3 tabs, so it should somehow be easier to navigate than going through menu each time.
I guess having a page with all 3 randomizations at the same time is not where you want the app to go? (in addition of the 3 existing pages)

**Comment by on3iro** [comment]
Hm, we could add two buttons to each of the randomizers (like _left_ and _right_) to cycle between `nemesis`, `mages` and `supply`.
@jannydiamond could you create some kind of wireframe or something a long those lines of how that would look? This does not have priority right now, I will probably schedule this feature for 1.7.0.
But it might be cool to have something like this eventually

**Comment by Serneum** [comment]
Just going to toss in my support for navigation on the bottom. It's one less click each time I want to move around the app, allows me to jump around to the different pages and see the information I want quickly, and is something I've found I really like through other apps (like BG Stats).

**Comment by on3iro** [comment]
@jquelin @Serneum would you still leave the drawer navigation in there? Or would you prefer a tab bottom navigation between nemesis/mages/supply/turnorder and a way to access the settings through a dot menu inside the top navigation?

**Comment by jquelin** [comment]
If there are buttons, I'm not sure the menu navigation is still needed.

**Comment by Serneum** [comment]
I would agree that there would be no need for a menu. I would probably do Nemeses, Mages, Supply, Turn Order, Settings. Or, put a gear icon in the header somewhere that flips to a settings page. I mentioned it before, but I think BG Stats has a good flow for where buttons should be

**Comment by jannydiamond** [comment]
I will come up with some wireframes of the different approaches. I am not sure about the bottom navigation because of the floating button at the bottom. But i guess we get a better impression how to do it when we have some pictures to discuss :)

**Comment by on3iro** [comment]
@jquelin released with 2.0.0 :)
